spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quote
    username: root
    password: Aa000000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 1000MB
server:
  port: 1234
thymeleaf:
  cache: false
  prefix: classpath:/templates/
  suffix: .html
  encoding: UTF-8
  mode: HTML5
jwt:
  secret: QeDw59VfDM6YvJCbo1zMCGplBZNxIFYrBTXD3wPBa96J1SkhTIzKNIGHTibyhYv56akicDWEDu2plVNogTn1UNgj7T8louHBzLebDnFF0F7V4d0FoIQ72H9L