spring:
  profiles:
    active: dev
    include:
  jpa:
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 1000MB
logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener:
            logging:
              SLF4JQueryLoggingListener: debug